services:
  postgres:
    image: postgres:16
    container_name: employee-manager-postgres
    restart: always
    environment:
      POSTGRES_DB: employee_manager
      POSTGRES_USER: employee_user
      POSTGRES_PASSWORD: employee_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
